[package]
name = "sqloxide"
version = "0.3.38"
authors = ["Will Eaton <me@wseaton.com>"]
edition = "2018"

[lib]
name = "sqloxide"
crate-type = ["cdylib"]

[dependencies]
pythonize = "0.19"
serde = "1.0.171"

[dependencies.pyo3]
version = "0.19.1"
features = ["extension-module"]

[dependencies.illumex-sqlparser]
version = "0.38.3"
features = ["serde", "visitor"]
